<a href="https://colab.research.google.com/github/Neilus03/Task-assignment-problem/blob/Neil%C2%B4s-branch/Random_forest_translators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [ ]:
data = pd.read_csv("/content/data.csv")

data.head(5)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360121 entries, 0 to 360120
Data columns (total 24 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   PROJECT_ID                   360121 non-null  object
 1   PM                           360121 non-null  object
 2   TASK_ID                      360121 non-null  int64
 3   START                        360121 non-null  object
 4   END                          360121 non-null  object
 5   TASK_TYPE                    360121 non-null  object
 6   SOURCE_LANG                  360121 non-null  object
 7   TARGET_LANG                  360121 non-null  object
 8   TRANSLATOR                   360121 non-null  object
 9   ASSIGNED                     360121 non-null  object
 10  READY                        360121 non-null  object
 11  WORKING                      360121 non-null  object
 12  DELIVERED                    360121 non-null  object
 13  RECEIVED                     360121 non-null  object
 14  CLOSE                        360121 non-null  object
 15  FORECAST                     360121 non-null  float64
 16  HOURLY_RATE                  360120 non-null  float64
 17  COST                         360120 non-null  float64
 18  QUALITY_EVALUATION           360120 non-null  float64
 19  MANUFACTURER                 360120 non-null  object
 20  MANUFACTURER_SECTOR          360120 non-null  object
 21  MANUFACTURER_INDUSTRY_GROUP  360120 non-null  object
 22  MANUFACTURER_INDUSTRY        360120 non-null  object
 23  MANUFACTURER_SUBINDUSTRY     360120 non-null  object
dtypes: float64(4), int64(1), object(19)
memory usage: 65.9+ MB

In [9]:



# Drop datetime columns
datetime_columns = ['START', 'END', 'ASSIGNED', 'READY', 'WORKING', 'DELIVERED', 'RECEIVED', 'CLOSE']
data = data.drop(datetime_columns, axis=1)

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

                      precision    recall  f1-score   support

               Aaron       0.00      0.00      0.00         4
        Abdon Isaias       0.44      0.53      0.48       899
            Abelardo       0.44      0.17      0.24       178
       Acacio Poncio       0.18      0.37      0.24       803
           Adalberto       0.50      0.02      0.04        45
              Agueda       0.23      0.02      0.03       946
            Agustina       0.20      0.50      0.29         4
                Aide       0.00      0.00      0.00         2
         Aide Matias       0.00      0.00      0.00         6
                Aino       1.00      0.75      0.86        12
               Aisha       1.00      1.00      1.00         1
               Alain       0.00      0.00      0.00         1
           Alejandro       0.13      0.13      0.13        45
               Alejo       0.00      0.00      0.00         3
        Alejo Esdras       0.00      0.00      0.00        16
          Alessandro       0.00      0.00      0.00         6
                Alex       0.19      0.03      0.06       321
           Alexander       0.00      0.00      0.00         9
             Alfonso       0.41      0.21      0.28       185
     Almudena Fiamma       0.34      0.55      0.42      1662
      Almudena Jorge       0.00      0.00      0.00         0
        Alonso Dimas       0.38      0.26      0.31       316
       Amaiur Lucano       0.00      0.00      0.00         1
              Amalia       0.50      1.00      0.67         5
         Amaro Salma       0.00      0.00      0.00        10
              Amelie       0.72      0.63      0.67        60
       Amelio Lazaro       0.00      0.00      0.00        59
         Ana Barbara       0.00      0.00      0.00         3
           Ana Clara       0.00      0.00      0.00         1
         Ana Daniela       0.34      0.32      0.33       160
        Ana Gabriela       0.00      0.00      0.00        66
         Ana Giselle       0.00      0.00      0.00         1
          Ana Jimena       0.00      0.00      0.00         3
           Ana Laura       0.27      0.01      0.02       381
           Ana Pilar       0.00      0.00      0.00         2
             Anabela       0.41      0.70      0.52        10
             Ananias       0.00      0.00      0.00         1
            Anatolio       0.25      0.00      0.01       208
  Anatolio Ildefonso       0.29      0.07      0.11        28
      Anatolio Josue       0.00      0.00      0.00         1
       Anatolio Rita       0.78      0.39      0.52        18
               Andre       1.00      0.33      0.50         3
             Andreas       0.00      0.00      0.00         1
              Andres       0.00      0.00      0.00         6
                 Ane       0.50      0.54      0.52       285
              Aniano       0.29      0.18      0.22        11
       Aniano Julian       0.12      0.06      0.08        62
       Anika Rosalia       0.00      0.00      0.00         5
                Anne       1.00      1.00      1.00         1
     Anselma Daciano       0.00      0.00      0.00       978
             Anselmo       0.00      0.00      0.00         1
                 Aoi       0.00      0.00      0.00         1
             Aouatif       0.50      1.00      0.67         2
    Aranzazu Ananias       0.00      0.00      0.00         8
             Ariadna       0.50      0.11      0.18       160
     Ariadna Laurina       0.30      0.04      0.08       950
        Ariadna Lino       0.00      0.00      0.00         2
      Ariadna Salvio       0.43      0.11      0.17        28
              Aritza       0.00      0.00      0.00         4
             Arnaldo       0.33      0.38      0.35         8
       Artemio Ramon       0.51      0.97      0.67       380
              Arturo       0.19      0.07      0.10       416
      Arturo Conrado       0.00      0.00      0.00         1
           Ascension       0.27      0.17      0.21       170
Aureliano Alejandria       0.00      0.00      0.00         7
        Aurelio Cayo       0.42      0.26      0.32       502
     Baldomero Enith       0.00      0.00      0.00         7
     Baldomero Fidel       0.00      0.00      0.00         6
            Balduino       0.50      0.30      0.37        27
            Baptiste       0.45      0.96      0.62        26
           Bartolome       0.67      0.47      0.55       541
   Bartolome Enrique       0.00      0.00      0.00         1
             Basileo       0.41      0.13      0.19       618
             Beatriz       0.00      0.00      0.00       367
               Belen       0.00      0.00      0.00         6
     Belen Fortunato       0.00      0.00      0.00         7
           Benedicto       0.00      0.00      0.00        20
     Benedicto Dimas       0.00      0.00      0.00        12
      Benigno Oliver       0.00      0.00      0.00        18
             Bernabe       0.47      0.34      0.40       123
            Bernarda       0.00      0.00      0.00        18
            Bernardo       0.47      0.17      0.25        48
       Bianca Elissa       0.00      0.00      0.00         3
                Biel       0.08      0.05      0.06        22
       Blas Heraclio       0.50      0.14      0.22         7
               Brais       0.25      0.18      0.21        68
             Cameron       0.00      0.00      0.00         3
              Carles       0.22      0.18      0.19       472
              Carlos       0.00      0.00      0.00        12
      Carlos Eduardo       0.00      0.00      0.00        11
             Casiano       0.00      0.00      0.00       875
           Catherine       0.00      0.00      0.00         1
                Cayo       0.17      0.01      0.03        74
               Celso       0.44      0.71      0.54       633
       Celso Facundo       0.00      0.00      0.00         1
              Celton       0.56      0.31      0.40        16
             Charles       0.00      0.00      0.00         6
           Christian       0.27      0.44      0.33       245
         Christopher       0.00      0.00      0.00        26
              Cibran       0.00      0.00      0.00        11
        Ciro Cesareo       0.00      0.00      0.00         3
             Claudio       0.25      0.03      0.05        33
             Columba       0.46      0.09      0.16       128
      Columba Lucano       0.00      0.00      0.00         1
             Conrado       0.00      0.00      0.00         9
         Constantino       0.00      0.00      0.00        13
Constantino Kimberly       0.28      0.42      0.33       605
                Daan       0.67      1.00      0.80         2
             Daciano       0.00      0.00      0.00         2
               Dacio       0.00      0.00      0.00         4
      Daiana Casiano       0.33      0.19      0.24        79
              Dalila       0.46      0.49      0.48       176
              Damian       0.00      0.00      0.00        18
             Damiana       0.78      0.38      0.51        37
             Daniela       0.00      0.00      0.00         5
               Dario       0.57      0.77      0.65       835
               David       0.28      0.27      0.28        74
              Davide       0.42      0.59      0.49        46
           Demetrius       0.29      0.33      0.31         6
              Denise       0.00      0.00      0.00         5
     Diego Alejandro       0.00      0.00      0.00        56
        Dimas Rafael       0.28      0.24      0.26       139
              Dmitry       1.00      1.00      1.00         1
              Donato       0.00      0.00      0.00         1
             Edmundo       0.54      0.22      0.31       173
             Eduardo       0.89      0.89      0.89        19
               Ekain       0.00      0.00      0.00        25
        Elias Daiana       0.23      0.21      0.22        53
               Ellie       0.00      0.00      0.00         1
              Elodie       0.00      0.00      0.00         3
                Elsa       1.00      1.00      1.00         1
            Emiliano       0.00      0.00      0.00         2
                Emma       0.12      0.11      0.12         9
              Endika       0.73      0.30      0.42        27
               Eneko       0.00      0.00      0.00         3
               Enric       0.57      0.77      0.65       690
             Enrique       0.16      0.13      0.15       181
               Erica       0.00      0.00      0.00         3
               Erico       0.28      0.10      0.14       871
             Esiquio       0.43      0.47      0.45       133
     Esteban Yoselin       0.48      0.22      0.30      1422
    Estefania Romina       0.00      0.00      0.00         1
              Estela       0.41      0.61      0.49       525
               Ester       0.43      0.25      0.32       198
            Eustaqui       0.00      0.00      0.00         3
            Evaristo       0.00      0.00      0.00         6
      Exequiel Abdon       0.25      0.06      0.10       112
     Exequiel Sergio       0.50      0.25      0.33         8
        Fabian Itzel       0.00      0.00      0.00         1
             Fabiola       0.00      0.00      0.00        31
       Facundo Ivana       0.67      0.50      0.57         4
              Fausto       0.00      0.00      0.00        14
       Felipe Aldana       0.30      0.03      0.06       610
               Felix       0.00      0.00      0.00        96
             Ferland       0.00      0.00      0.00         1
              Fermin       0.00      0.00      0.00         4
              Fiamma       0.00      0.00      0.00         0
    Fiamma Baldomero       0.25      0.11      0.15       589
   Florencia Soledad       0.00      0.00      0.00        36
            Francesc       0.00      0.00      0.00        14
           Francesco       0.21      1.00      0.34         8
      Francisco Jose       0.30      0.13      0.18       144
    Francisco Miguel       0.15      0.18      0.16        90
               Franz       0.00      0.00      0.00         1
  Fulgencio Nahikari       0.12      0.02      0.03        66
            Gabriela       0.47      0.25      0.33       171
                Gala       0.82      0.95      0.88      3336
           Garikoitz       0.33      0.01      0.02        86
            Genoveva       0.00      0.00      0.00         2
               Gerda       0.00      0.00      0.00         2
              German       0.25      0.07      0.11        14
            Geronimo       0.00      0.00      0.00        10
            Gianluca       0.86      0.33      0.48        18
             Giovani       0.00      0.00      0.00         1
    Gisela Ildefonso       0.23      0.06      0.09       364
       Gregorio Luis       0.00      0.00      0.00        15
               Greta       0.00      0.00      0.00         1
   Guadalupe Enrique       0.00      0.00      0.00         2
               Guido       0.30      0.05      0.08       151
           Guillermo       0.22      0.10      0.14       103
              Haizea       0.00      0.00      0.00         5
              Hannah       0.60      0.16      0.25        19
              Haritz       0.00      0.00      0.00         6
              Hector       0.54      0.91      0.67        32
            Heraclio       0.48      0.10      0.17       868
   Hildegarda Leonor       0.12      0.05      0.07       104
            Honorato       0.33      0.25      0.29         4
             Honorio       0.33      0.02      0.04        52
            Humberto       0.33      0.38      0.35        39
                Iara       0.00      0.00      0.00         8
      Ignacio Agueda       0.00      0.00      0.00         1
  Ildefonso Ambrosio       0.49      0.61      0.54       521
  Ildefonso Priscila       0.00      0.00      0.00        40
     Inocencio Kenti       0.00      0.00      0.00        18
     Inocencio Lucas       0.46      0.61      0.53      4123
                Inti       0.00      0.00      0.00         3
              Ireneo       0.58      0.03      0.06       211
                Iria       0.00      0.00      0.00         3
               Isaac       0.19      0.05      0.08        93
     Isaias Venancio       0.35      0.08      0.13      2798
               Iskay       0.63      0.96      0.76       391
                Ivan       1.00      1.00      1.00         1
       Ivana Araceli       0.00      0.00      0.00         1
                 Ivo       0.00      0.00      0.00         6
       Ivon Patricio       0.67      0.29      0.40         7
       Ivon Raimundo       0.00      0.00      0.00         1
               James       0.75      0.27      0.40        11
                 Jan       0.87      0.93      0.90        28
        Jana Agustin       0.00      0.00      0.00         1
               Jaume       0.00      0.00      0.00        40
                Jean       0.50      0.05      0.10        19
            Jeremias       0.00      0.00      0.00        29
            Jeronimo       0.00      0.00      0.00        22
      Jeronimo Casio       0.00      0.00      0.00         1
              Jimena       0.00      0.00      0.00         1
      Jimena Arcadio       0.72      0.70      0.71       546
                Jing       1.00      0.75      0.86         4
               Joana       0.33      0.11      0.17        18
             Joaquim       0.70      0.44      0.54        70
             Joaquin       0.53      0.28      0.37        32
             Johanna       0.60      0.21      0.32        14
               Jonas       0.00      0.00      0.00         1
          Jonas Tito       0.17      0.05      0.07       104
               Jorge       0.00      0.00      0.00        86
    Josafat Emiliano       1.00      0.06      0.11        17
          Jose Angel       0.00      0.00      0.00        11
          Jose David       0.00      0.00      0.00       140
           Jose Luis       0.00      0.00      0.00         4
          Jose Ramon       0.00      0.00      0.00        17
   Josefina Catalina       0.20      0.35      0.26       391
              Joshua       0.59      0.30      0.40        33
                Juan       0.00      0.00      0.00         7
        Juan Alberto       0.00      0.00      0.00         1
        Juan Antonio       0.20      0.02      0.04        90
         Juan Carlos       0.20      0.07      0.10       507
      Juan Francisco       0.00      0.00      0.00         1
      Juan Guillermo       0.00      0.00      0.00         1
         Juan Rafael       0.27      0.16      0.20       239
          Juan Ramon       0.00      0.00      0.00         2
               Juana       1.00      1.00      1.00         1
        Karina Anais       0.00      0.00      0.00         3
           Katarzyna       1.00      1.00      1.00         1
              Keiran       0.44      0.29      0.35        41
               Kenti       0.60      0.10      0.17        31
               Killa       0.89      0.97      0.93       630
            Kimberly       0.50      0.03      0.06        29
        Kristal Rubi       0.07      0.03      0.04       107
               Kumya       0.00      0.00      0.00         6
                Lais       0.25      0.20      0.22         5
        Laura Isabel       0.00      0.00      0.00         4
    Laureano Facundo       0.22      0.16      0.18       372
      Laurina Rafael       0.37      0.51      0.43       653
   Lazaro Alejandria       0.40      0.67      0.50         6
       Leila Josafat       0.37      0.47      0.42       115
               Leire       0.00      0.00      0.00       197
      Leoncio Vanina       0.20      0.16      0.18       173
          Lidia Adon       0.00      0.00      0.00        15
             Lillian       0.30      0.11      0.16        27
             Lincoln       0.00      0.00      0.00         5
                Lino       0.61      0.53      0.57       967
       Lionel Yamila       0.25      0.11      0.15         9
                Luan       0.00      0.00      0.00         0
              Lucano       0.30      0.65      0.41      1043
               Lucas       1.00      0.04      0.07        26
         Lucas Belen       0.46      0.75      0.57        92
               Lucia       0.00      0.00      0.00        33
             Luciano       0.00      0.00      0.00         5
            Lucrecia       0.00      0.00      0.00        63
    Lucrecia Aquiles       0.27      0.19      0.22       106
         Luis Felipe       0.42      0.34      0.38      1339
             Macario       0.00      0.00      0.00         1
             Madison       0.37      0.12      0.18       256
       Maitane Adela       0.00      0.00      0.00         1
         Maite Usula       0.00      0.00      0.00        41
    Manuel Alejandro       0.00      0.00      0.00        35
       Marcelo Casio       0.00      0.00      0.00         1
     Marciano Daiana       0.22      0.17      0.19        12
               Marco       0.00      0.00      0.00         1
           Margarita       0.34      0.18      0.24       281
     Margarita Jesus       0.00      0.00      0.00        16
     Maria Alexandra       0.45      0.22      0.30        41
      Maria Cristina       0.00      0.00      0.00         6
      Maria Fernanda       0.00      0.00      0.00         1
        Maria Isabel       0.31      0.24      0.27       140
           Marianela       0.00      0.00      0.00         1
               Marie       0.78      0.90      0.83        81
        Mario Camilo       0.00      0.00      0.00         1
         Mario Ramon       0.13      0.03      0.05        60
              Markel       0.41      0.90      0.56      2746
              Markus       0.22      0.67      0.33         6
               Marli       0.00      0.00      0.00         0
               Marti       0.56      0.27      0.36        93
             Martina       0.00      0.00      0.00         1
             Matilde       0.00      0.00      0.00         4
              Matteo       0.00      0.00      0.00         1
            Mauricio       0.00      0.00      0.00        24
  Maximiliano Vanina       0.14      0.29      0.19         7
              Maximo       0.30      0.38      0.34       657
   Maximo Inmaculada       0.44      0.04      0.08        92
                Maya       1.00      1.00      1.00         1
            Mercedes       0.18      0.09      0.12        22
    Mercedes Leandro       0.00      0.00      0.00         1
       Miah Virgilio       0.21      0.07      0.11       149
              Michel       0.50      0.14      0.22         7
           Miercoles       0.00      0.00      0.00        13
        Miguel Angel       0.00      0.00      0.00         1
               Minji       0.00      0.00      0.00         2
              Mireia       0.21      0.42      0.28        67
      Monica Rogelio       0.67      0.29      0.40         7
       Monica Soraia       0.00      0.00      0.00         1
          Montserrat       0.00      0.00      0.00         5
            Muhammad       1.00      1.00      1.00         1
               Nacho       0.39      0.35      0.37       586
              Nahuel       1.00      1.00      1.00         2
       Narciso Oriol       0.33      0.50      0.40         2
             Natalie       0.81      0.43      0.56       331
    Nemesio Laureano       0.41      0.32      0.36       142
      Nemesio Melany       0.00      0.00      0.00        40
            Nicholas       0.75      0.72      0.73        86
     Nieves Leocadia       0.28      0.79      0.42      1477
             Nikolay       0.78      1.00      0.88         7

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:

# Identify categorical columns for one-hot encoding
categorical_columns = ['PM', 'TASK_TYPE', 'SOURCE_LANG', 'TARGET_LANG', 'MANUFACTURER', 'MANUFACTURER_SECTOR',
                       'MANUFACTURER_INDUSTRY_GROUP', 'MANUFACTURER_INDUSTRY', 'MANUFACTURER_SUBINDUSTRY']

In [ ]:

# Prepare the features and target variable
X = data.drop("TRANSLATOR", axis=1)
y = data["TRANSLATOR"]

In [ ]:

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Create a column transformer for one-hot encoding
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_columns)
    ])

In [ ]:
# Create a pipeline that performs one-hot encoding and then trains the random forest classifier
pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))])

In [ ]:
# Train the model using the pipeline
pipeline.fit(X_train, y_train)

# Make predictions on the test dataset
y_pred = pipeline.predict(X_test)

# Evaluate the performance of the model
print(classification_report(y_test, y_pred))

In [10]:
import numpy as np

# Calculate the custom accuracy score
correct_predictions = np.sum(y_test == y_pred)
total_predictions = len(y_test)
custom_accuracy = correct_predictions / total_predictions

print(f"Custom accuracy: {custom_accuracy:.2f}")

Custom accuracy: 0.42